# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'


stages:

  - stage: Build
    displayName: Build Application
    jobs:
      - job:
        displayName: build job
        steps:  
        - task: NuGetToolInstaller@0
          displayName: 'Use NuGet 6.x'
          inputs:
            versionSpec: 6.x
        - task: NuGetCommand@2
          displayName: 'NuGet restore'
          inputs:
            restoreSolution: 'src/ChooseYourPokemon.sln'
            restoreDirectory: '$(System.DefaultWorkingDirectory)/package'
        - task: XamarinAndroid@1
          displayName: 'Build Xamarin.Android'
          inputs:
            projectFile: 'src/app/ChooseYourPokemon.Android/ChooseYourPokemon.Android.csproj'
            outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)/AndroidOutput'
            configuration: '$(BuildConfiguration)'
            msbuildVersionOption: latest
            msbuildArchitectureOption: 'x64'
            jdkVersionOption: 1.11
        - task: AndroidSigning@3
          displayName: 'Signing and aligning'
          inputs:
            apkFiles: '$(build.binariesdirectory)/$(BuildConfiguration)/AndroidOutput/*.aab'
            apksignerKeystoreFile: 'ChooseYouPokemon.keystore'
            apksignerKeystorePassword: '$(key_password)'
            apksignerKeystoreAlias: '$(key_alias)'
            apksignerKeyPassword: '$(key_password)'
            apksignerArguments: '--verbose  --min-sdk-version 21'  
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: android-artifact'
          inputs:
            PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)/AndroidOutput'
            ArtifactName: 'android-artifact'

  - stage: Test
    displayName: Test Application
    dependsOn: Build
    jobs:
      - job:
        displayName: Coverage job
        steps:  
        - task: UseDotNet@2
          displayName: 'Use .Net 7'
          inputs:
            packageType: 'sdk'
            version: '7.0.x'    
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'Sonar Demo'
            organization: 'fagnerdemos'
            scannerMode: 'MSBuild'
            projectKey: 'fagnerdemos_anima-tech-week'
            projectName: 'Anima Tech Week'    
        - task: DotNetCoreCLI@2
          displayName: 'Build Xamarin Core'
          inputs:
            command: 'build'
            projects: 'src/app/ChooseYourPokemon/ChooseYourPokemon.csproj'
        - task: DotNetCoreCLI@2
          displayName: 'Unit Test'
          inputs:
            command: test
            projects: 'src/ChooseYourPokemon.UnitTest/ChooseYourPokemon.UnitTest.csproj'      
        - task: SonarCloudAnalyze@1
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
        - task: SonarCloudPublish@1
          inputs:
            pollingTimeoutSec: '300'

      - job:
        pool: 
          vmImage: windows-2022
        displayName: UI Test job
        steps: 
        - download: current
          artifact: android-artifact     
        - task: NuGetToolInstaller@0
          displayName: 'Use NuGet 6.x'
          inputs:
            versionSpec: 6.x
        - task: NuGetCommand@2
          displayName: 'NuGet restore'
          inputs:
            restoreSolution: 'src/ChooseYourPokemon.sln'
            restoreDirectory: '$(System.DefaultWorkingDirectory)/package'
        - task: NodeTool@0
          displayName: 'Use Node 10.x.x'
          inputs:
            versionSpec: 10.x.x
        - task: MSBuild@1
          displayName: 'Build UITest'
          inputs:
            solution: 'src/ChooseYourPokemon.UITest/ChooseYourPokemon.UITest.csproj'
            msbuildVersion: 17.0
            msbuildArchitecture: x64
            configuration: '$(BuildConfiguration)'
            msbuildArguments: '/p:OutputPath=$(build.binariesdirectory)/$(BuildConfiguration)/TestdOutput'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: uitest-artifact'
          inputs:
            PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)/TestdOutput'
            ArtifactName: 'ui-test-artifact'
        - task: AppCenterTest@1
          displayName: 'Test with Visual Studio App Center'
          enabled: false
          inputs:
            appFile: '$(Pipeline.Workspace)/android-artifact/com.chooseyourpokemon.aab'
            artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
            frameworkOption: 'uitest'
            uiTestBuildDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)/TestdOutput/'
            uiTestToolsDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)/TestdOutput/'
            prepareOptions: '--debug'
            credentialsOption: 'serviceEndpoint'
            serverEndpoint: 'app center account'
            appSlug: 'Anima-Tech-Week/Lab-Pokemon'
            devices: 'Anima-Tech-Week/validate-max-min'
            series: 'demos'
            localeOption: 'en_US'